theme: jekyll-theme-leap-day
title: LPQ Blog
email: Liu_Peiqi#163.com (# -> @)
descirption: > Liu Peiqi some blog.
permalink: /blog/:year/:month/:title
timezone: +0800
incremental: true
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: Liu Peiqi
#
